name: Frontend Deployment to the Azure Storage
on:
  push:
    branches: [frontend]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Azure Login ğŸš¶â€â™‚ï¸
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload to Azure Blog Storage ğŸ“¦
        uses: azure/CLI@v1
        with:
          inlineScript: az storage blob upload-batch -s website/ -d '$web' --account-name cdrcestorage --auth-mode key
      - name: Azure Logout ğŸƒâ€â™‚ï¸
        run: az logout
        if: always()